//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalista.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kalista.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        public static string ColumnIndex_Day0 {
            get {
                return ResourceManager.GetString("ColumnIndex_Day0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        public static string ColumnIndex_RoomNumber {
            get {
                return ResourceManager.GetString("ColumnIndex_RoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 港币,新西兰元,澳大利亚元,美元,欧元,加拿大元,英镑,日元,新加坡元,瑞士法郎 的本地化字符串。
        /// </summary>
        public static string CurrencyNames {
            get {
                return ResourceManager.GetString("CurrencyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://fx.cmbchina.com/Hq/ 的本地化字符串。
        /// </summary>
        public static string CurrencyRateSite {
            get {
                return ResourceManager.GetString("CurrencyRateSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?&lt;=&lt;tr&gt;\s*&lt;td class=\x22fontbold\x22&gt;\s*Currency\s*&lt;/td&gt;\s*(?:&lt;td[^&lt;&gt;]*&gt;[^&lt;&gt;]*&lt;/td&gt;\s*){5}&lt;td class=\x22numberright\x22&gt;\s*)[\d.]+(?=\s*&lt;/td&gt;) 的本地化字符串。
        /// </summary>
        public static string CurrencyRegexString {
            get {
                return ResourceManager.GetString("CurrencyRegexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency 的本地化字符串。
        /// </summary>
        public static string CurrencyRegexStringReplaceKeyword {
            get {
                return ResourceManager.GetString("CurrencyRegexStringReplaceKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        public static string DayRowIndex {
            get {
                return ResourceManager.GetString("DayRowIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap dep_0 {
            get {
                object obj = ResourceManager.GetObject("dep_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap dep_100 {
            get {
                object obj = ResourceManager.GetObject("dep_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap dep_custom {
            get {
                object obj = ResourceManager.GetObject("dep_custom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap fmt_bordersAll {
            get {
                object obj = ResourceManager.GetObject("fmt_bordersAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap fmt_itinialize {
            get {
                object obj = ResourceManager.GetObject("fmt_itinialize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap fmt_shapeAS {
            get {
                object obj = ResourceManager.GetObject("fmt_shapeAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap qa_sheet_dailyRS {
            get {
                object obj = ResourceManager.GetObject("qa_sheet_dailyRS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap qa_sheet_deposit {
            get {
                object obj = ResourceManager.GetObject("qa_sheet_deposit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 9 的本地化字符串。
        /// </summary>
        public static string Report_Columns {
            get {
                return ResourceManager.GetString("Report_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※注：预付微信请标a，支付宝请标b，银行卡转账请标c，并把金额写起,谢谢！如a-400 的本地化字符串。
        /// </summary>
        public static string Report_Content {
            get {
                return ResourceManager.GetString("Report_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 25 的本地化字符串。
        /// </summary>
        public static string Report_ReceiptCount {
            get {
                return ResourceManager.GetString("Report_ReceiptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前台收入表    {0}年{1}月{2}日{3} 的本地化字符串。
        /// </summary>
        public static string Report_Title {
            get {
                return ResourceManager.GetString("Report_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 101-1,101-1,101-3,101-4,102-1, 的本地化字符串。
        /// </summary>
        public static string RoomNoString {
            get {
                return ResourceManager.GetString("RoomNoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通6人间,普通4人间,普通单人,普通三人间,标准双床间,标准大床房,标准三人间,家庭房,普通双人间,普通大床房 的本地化字符串。
        /// </summary>
        public static string RoomTypeString {
            get {
                return ResourceManager.GetString("RoomTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 81 的本地化字符串。
        /// </summary>
        public static string RowIndex_Max {
            get {
                return ResourceManager.GetString("RowIndex_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        public static string RowIndex_Min {
            get {
                return ResourceManager.GetString("RowIndex_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_checkedOut {
            get {
                object obj = ResourceManager.GetObject("rs_checkedOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_default {
            get {
                object obj = ResourceManager.GetObject("rs_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_delete_res {
            get {
                object obj = ResourceManager.GetObject("rs_delete_res", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_delete_selected {
            get {
                object obj = ResourceManager.GetObject("rs_delete_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_delete_shape {
            get {
                object obj = ResourceManager.GetObject("rs_delete_shape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_F3C_hide {
            get {
                object obj = ResourceManager.GetObject("rs_F3C_hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_F3C_show {
            get {
                object obj = ResourceManager.GetObject("rs_F3C_show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_noShow {
            get {
                object obj = ResourceManager.GetObject("rs_noShow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_paid {
            get {
                object obj = ResourceManager.GetObject("rs_paid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_pasteRes {
            get {
                object obj = ResourceManager.GetObject("rs_pasteRes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_pickUp {
            get {
                object obj = ResourceManager.GetObject("rs_pickUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_prepaid {
            get {
                object obj = ResourceManager.GetObject("rs_prepaid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_TRS_hide {
            get {
                object obj = ResourceManager.GetObject("rs_TRS_hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_TRS_show {
            get {
                object obj = ResourceManager.GetObject("rs_TRS_show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap rs_unpaid {
            get {
                object obj = ResourceManager.GetObject("rs_unpaid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Mori,Eki,Tank,Cindy,May,Kevin,Mary,Edward 的本地化字符串。
        /// </summary>
        public static string StaffSet {
            get {
                return ResourceManager.GetString("StaffSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 收入报表模板 {
            get {
                object obj = ResourceManager.GetObject("收入报表模板", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
